---
- name: Validating BIG-IP Health
  hosts: ltm01
  connection: local
  vars_files: web_app.yml
  tasks:
    - name: Collect Virtual Server Facts from BIG-IP
      bigip_device_facts:
        gather_subset:
          - virtual-servers
        provider: "{{ conn_parameters }}"
      register: bigip_app_facts

    # - debug: var=bigip_app_facts.virtual_servers

    - name: Create Virtual Server Name Fact
      set_fact:
        vs_name: "{{ website }}_{{ vip_port }}_VS"

    - name: Create App Virtual Servers
      set_fact:
        app_vs: "{{ app_vs | default([]) + 
                    bigip_app_facts.virtual_servers | selectattr('name','equalto',vs_name) | list }}" 

    # - debug: var=app_vs

    - name: Validate Virtual Address Status
      assert:
        that:
          - item.enabled == 'yes'
          - item.destination_address == vip
          - item.destination_port == vip_port
        fail_msg: " {{ item.name }} is No Setup Correctly"  
      loop: "{{app_vs}}"

