---
- name: Install Python3
  package:
    name: python3
    state: present

- name: Check if python Link already exists
  stat:
    path: /usr/bin/python
  register: python_link
  
- name: Create Soft Link to Python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  when: not python_link.stat.exists

- name: Install Python PIP System Package
  package:
    name: python3-pip
    state: present

- name: Add Ansible Repo
  pip:
    executable: pip3  
    name: ansible
    version: "{{ ansible_version }}"

