vpc_name: EU_Prod_Public_VPC
vpc_cidr: 10.3.0.0/16
igw_name: eu_prod_igw

vpc_subnets:
  eu-prod-public-a:
    cidr: 10.3.1.0/24
    az: "{{ aws_region }}a"
    tags: "{{ vpc_tags }}"
    public: true

  eu-prod-public-b:
    cidr: 10.3.2.0/24
    az: "{{ aws_region}}b"
    tags: "{{ vpc_tags }}"
    public: true

route_table:
  tags:
    Name: eu_prod_public_rt
  igw:
    - dest: 0.0.0.0/0
      gateway_id: "{{ igw_id }}"
  public:
      - eu-prod-public-a
      - eu-prod-public-a

network_acls:
  - name: EU_Prod_ACLs
    subnets: "{{ vpc_subnets.keys() | list }}"
    ingress_rules:
      - [100,'tcp','allow','0.0.0.0/0',null,null,80,80]
      - [200,'tcp','allow','0.0.0.0/0',null,null,443,443]
    egress_rules:
      - [100,'all', 'allow', '0.0.0.0/0', null, null, null, null]

vpc_tags:
  role: prod
  region: eu


