---
- name: Populate NetBox DataBase
  hosts: dc1,dc2
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
    netbox_state: present
  tasks:
    - import_role: 
        name: build_netbox_db

