---
- name: Deploy Ansible AWX
  hosts: awx
  become: yes
  tasks:
    - name: Install Ansible
      import_role:  
        name: deploy_ansible
      tags: ansible

    - name: Install Python PIP
      import_role:  
        name: deploy_pip
      tags: pip

    - name: Install Docker
      import_role:  
        name: deploy_docker
      tags: docker

    - name: Install Nodjs
      import_role:  
        name: deploy_nodejs
      tags: nodejs

    - name: Install AWS
      import_role:
        name: deploy_awx
      tags: awx

