ansible_network_os: eos
#ansible_connection: httpapi 
ansible_user: ansible
ansible_ssh_pass: ansible123
# ansible_become: yes
# ansible_become_method: enable
# ansible_httpapi_use_ssl: yes
# ansible_httpapi_validate_certs: no
