---
- name: Upgrade PIP package
  pip:
    executable: pip3
    name: pip
    extra_args: --upgrade

- name: Install Python packages
  pip:
    executable: pip3
    name: "{{ item }}"
  loop: "{{ python_packages }}"
