---
- name: " Generate and Deploy Configuration on All Devices"
  hosts: sp_core
  tasks:
    - name: Build Device Configuration 
      import_role:
        name: build_router_config
      delegate_to: localhost
      tags: build  
        
    - name: "Deploy Configuration"
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        dev_os: "{{ ansible_network_os }}"
        config_file: "{{config_dir}}/{{ inventory_hostname }}.cfg"
        diff_file: "{{ config_diff_dir}}/{{ inventory_hostname }}_diff.txt"
        commit_changes: "{{commit | default('no')}}"
        replace_config: yes
      register: napalm_config
      tags: deploy, never

    # - debug: var=napalm_config
    #   tags: deploy, never



