---
- name: " Validating Network State via NAPALM"
  hosts: pe
  tasks:
    - name: "P1T1: Validation with NAPALM"
      napalm_validate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        dev_os: "{{ ansible_network_os }}"
        validation_file: "napalm_validate/{{ inventory_hostname}}.yml"
      ignore_errors: true
      register: net_validate
    
    - name: Create Compliance Report Folder
      file: path=compliance_folder state=directory

    - name: Clean last compliance Report
      file: path=compliance_folder/{{inventory_hostname}}.txt state=absent

    - name: Create Compliance Report
      copy:
        content: "{{ net_validate.compliance_report | to_nice_yaml }}"
        dest: "compliance_folder/{{ inventory_hostname }}.txt"
