---
- name: "Generate Interface Configuration"
  template:
    src: "{{ansible_network_os}}/intf.j2"
    dest: "{{config_dir}}/{{ inventory_hostname }}/01_intf.cfg"
  delegate_to: localhost

- name: "Push configuration to JunOS Devices"
  junos_config:
    src: "{{config_dir}}/{{ inventory_hostname }}/01_intf.cfg"




