---
- name: Decommision GCP Resources
  hosts: all
  connection: local
  gather_facts: no
  force_handlers: True
  environment:
    GCP_SERVICE_ACCOUNT_FILE: "{{ service_account_file }}"
    GCP_AUTH_KIND: 'serviceaccount'
  vars_files:
    - gcp_account_info.yml
  tasks:
    - name: Read the Vault Encrypted JSON File
      copy:
        content: "{{ lookup('file','gcp-ansible-secret.json') }}"
        dest: "{{ service_account_file }}"
      notify: Clean tmp Decrypted Files
      tags: always

    - name: Get VPC Facts
      gcp_compute_network_facts:
        project: "{{ project }}"
      register: gcp_vpc
      tags: 
        - gcp_route
        - gcp_subnet
        - gcp_fw_rules

    - name: Delete Instances
      gcp_compute_instance:
        name: "{{ node.name | regex_replace('_','-') }}"
        zone: "{{ node.zone }}"
        project: "{{ project }}"
        state: absent
      loop: "{{ compute_nodes }}"
      loop_control:
        loop_var: node
        label: "{{node.name}}"

    - name: Delete disks for Instances
      gcp_compute_disk:
        name: "{{ node.name | regex_replace('_','-') }}-disk"
        zone: "{{ node.zone }}"
        project: "{{ project }}"
        state: absent
      loop: "{{ compute_nodes }}"
      loop_control:
        loop_var: node
        label: "{{node.name}}"

    - name: Delete All Firewall Rules
      gcp_compute_firewall:
        name: "{{ rule.name | regex_replace('_','-') }}"
        network: "{{ gcp_vpc }}"
        project: "{{ project }}"
        state: absent
      loop: "{{ fw_rules }}"
      loop_control:
        loop_var: rule
      tags: gcp_fw_rules

    - name: Delete all Routes
      gcp_compute_route:
        name: "{{ route.name }}"
        dest_range: "{{ route.dest}}"
        network: "{{ gcp_vpc }}"
        project: "{{ project }}"
        state: absent
      loop: "{{ custom_routes }}"
      loop_control:
        loop_var: route
      when: 
      - custom_routes is defined
      tags: 
        - gcp_route

    - name: Delete GCP Subnets
      gcp_compute_subnetwork:
        name: "{{ subnet.name }}"
        ip_cidr_range: "{{ subnet.cidr }}"
        network: "{{ gcp_vpc }}"
        region: "{{ subnet.region }}"
        project: "{{ project }}"
        state: absent
      loop: "{{ subnets }}"
      loop_control:
        loop_var: subnet
      tags: 
        - gcp_subnet

    - name: Delete GCP VPC
      gcp_compute_network:
        name: "{{ vpc_name | regex_replace('_','-') }}"
        project: "{{ project }}"
        state: absent
      tags:
        - gcp_vpc

  handlers:
    - name: Clean tmp Decrypted Files
      file: 
        path: "{{ service_account_file }}"  
        state: absent