- name: "Generate Global Config Data"
  blockinfile:
    block: "{{ lookup('template','dc_fabric.j2') }}" 
    path: "group_vars/all.yml"
    create: yes
  run_once: yes

- name: "Generate BGP Specific Data"
  blockinfile:
    block: "{{ lookup('template','bgp.j2') }}" 
    path: "host_vars/{{ inventory_hostname }}/underlay_bgp.yml"
    create: yes